/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace Types {
  export type WithdrawalTransactionStruct = {
    nonce: BigNumberish;
    sender: string;
    target: string;
    value: BigNumberish;
    gasLimit: BigNumberish;
    data: BytesLike;
  };

  export type WithdrawalTransactionStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    nonce: BigNumber;
    sender: string;
    target: string;
    value: BigNumber;
    gasLimit: BigNumber;
    data: string;
  };

  export type OutputRootProofStruct = {
    version: BytesLike;
    stateRoot: BytesLike;
    messagePasserStorageRoot: BytesLike;
    latestBlockhash: BytesLike;
  };

  export type OutputRootProofStructOutput = [string, string, string, string] & {
    version: string;
    stateRoot: string;
    messagePasserStorageRoot: string;
    latestBlockhash: string;
  };
}

export interface OasysPortalInterface extends utils.Interface {
  functions: {
    "GUARDIAN()": FunctionFragment;
    "L2_ORACLE()": FunctionFragment;
    "SYSTEM_CONFIG()": FunctionFragment;
    "depositTransaction(address,uint256,uint64,bool,bytes)": FunctionFragment;
    "donateETH()": FunctionFragment;
    "finalizeWithdrawalTransaction((uint256,address,address,uint256,uint256,bytes))": FunctionFragment;
    "finalizeWithdrawalTransactions((uint256,address,address,uint256,uint256,bytes)[])": FunctionFragment;
    "finalizedWithdrawals(bytes32)": FunctionFragment;
    "guardian()": FunctionFragment;
    "initialize(bool)": FunctionFragment;
    "initializeWithRelayer(bool,address)": FunctionFragment;
    "isOutputFinalized(uint256)": FunctionFragment;
    "l2Oracle()": FunctionFragment;
    "l2Sender()": FunctionFragment;
    "messageRelayer()": FunctionFragment;
    "minimumGasLimit(uint64)": FunctionFragment;
    "params()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "proveWithdrawalTransaction((uint256,address,address,uint256,uint256,bytes),uint256,(bytes32,bytes32,bytes32,bytes32),bytes[])": FunctionFragment;
    "provenWithdrawals(bytes32)": FunctionFragment;
    "setMessageRelayer(address)": FunctionFragment;
    "systemConfig()": FunctionFragment;
    "unpause()": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "GUARDIAN"
      | "L2_ORACLE"
      | "SYSTEM_CONFIG"
      | "depositTransaction"
      | "donateETH"
      | "finalizeWithdrawalTransaction"
      | "finalizeWithdrawalTransactions"
      | "finalizedWithdrawals"
      | "guardian"
      | "initialize"
      | "initializeWithRelayer"
      | "isOutputFinalized"
      | "l2Oracle"
      | "l2Sender"
      | "messageRelayer"
      | "minimumGasLimit"
      | "params"
      | "pause"
      | "paused"
      | "proveWithdrawalTransaction"
      | "provenWithdrawals"
      | "setMessageRelayer"
      | "systemConfig"
      | "unpause"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "GUARDIAN", values?: undefined): string;
  encodeFunctionData(functionFragment: "L2_ORACLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SYSTEM_CONFIG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositTransaction",
    values: [string, BigNumberish, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "donateETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawalTransaction",
    values: [Types.WithdrawalTransactionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdrawalTransactions",
    values: [Types.WithdrawalTransactionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizedWithdrawals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "guardian", values?: undefined): string;
  encodeFunctionData(functionFragment: "initialize", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "initializeWithRelayer",
    values: [boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isOutputFinalized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "l2Oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "l2Sender", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "messageRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumGasLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "params", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proveWithdrawalTransaction",
    values: [
      Types.WithdrawalTransactionStruct,
      BigNumberish,
      Types.OutputRootProofStruct,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "provenWithdrawals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMessageRelayer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "systemConfig",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "GUARDIAN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "L2_ORACLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SYSTEM_CONFIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donateETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawalTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdrawalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizedWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guardian", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeWithRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOutputFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "l2Oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "l2Sender", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "params", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proveWithdrawalTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "provenWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMessageRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "MessageRelayerSet(address)": EventFragment;
    "Paused(address)": EventFragment;
    "TransactionDeposited(address,address,uint256,bytes)": EventFragment;
    "Unpaused(address)": EventFragment;
    "WithdrawalFinalized(bytes32,bool)": EventFragment;
    "WithdrawalProven(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MessageRelayerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransactionDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalFinalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalProven"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface MessageRelayerSetEventObject {
  relayer: string;
}
export type MessageRelayerSetEvent = TypedEvent<
  [string],
  MessageRelayerSetEventObject
>;

export type MessageRelayerSetEventFilter =
  TypedEventFilter<MessageRelayerSetEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface TransactionDepositedEventObject {
  from: string;
  to: string;
  version: BigNumber;
  opaqueData: string;
}
export type TransactionDepositedEvent = TypedEvent<
  [string, string, BigNumber, string],
  TransactionDepositedEventObject
>;

export type TransactionDepositedEventFilter =
  TypedEventFilter<TransactionDepositedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface WithdrawalFinalizedEventObject {
  withdrawalHash: string;
  success: boolean;
}
export type WithdrawalFinalizedEvent = TypedEvent<
  [string, boolean],
  WithdrawalFinalizedEventObject
>;

export type WithdrawalFinalizedEventFilter =
  TypedEventFilter<WithdrawalFinalizedEvent>;

export interface WithdrawalProvenEventObject {
  withdrawalHash: string;
  from: string;
  to: string;
}
export type WithdrawalProvenEvent = TypedEvent<
  [string, string, string],
  WithdrawalProvenEventObject
>;

export type WithdrawalProvenEventFilter =
  TypedEventFilter<WithdrawalProvenEvent>;

export interface OasysPortal extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OasysPortalInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Address that has the ability to pause and unpause withdrawals. This will be removed in the         future, use `guardian` instead.
     */
    GUARDIAN(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Address of the L2OutputOracle contract. This will be removed in the         future, use `l2Oracle` instead.
     */
    L2_ORACLE(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Address of the SystemConfig contract. This will be removed in the         future, use `systemConfig` instead.
     */
    SYSTEM_CONFIG(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Accepts deposits of ETH and data, and emits a TransactionDeposited event for use in         deriving deposit transactions. Note that if a deposit is made by a contract, its         address will be aliased when retrieved using `tx.origin` or `msg.sender`. Consider         using the CrossDomainMessenger contracts for a simpler developer experience.
     * @param _data Data to trigger the recipient with.
     * @param _gasLimit Amount of L2 gas to purchase by burning gas on L1.
     * @param _isCreation Whether or not the transaction is a contract creation.
     * @param _to Target address on L2.
     * @param _value ETH value to send to the recipient.
     */
    depositTransaction(
      _to: string,
      _value: BigNumberish,
      _gasLimit: BigNumberish,
      _isCreation: boolean,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Accepts ETH value without triggering a deposit to L2.         This function mainly exists for the sake of the migration between the legacy         Optimism system and Bedrock.
     */
    donateETH(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    finalizeWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    finalizeWithdrawalTransactions(
      _txs: Types.WithdrawalTransactionStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * A list of withdrawal hashes which have been successfully finalized.
     */
    finalizedWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    guardian(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Initializer.
     */
    initialize(
      _paused: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Initalize with setting messager relayer
     */
    initializeWithRelayer(
      _paused: boolean,
      _messageRelayer: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Determine if a given output is finalized.         Reverts if the call to L2_ORACLE.getL2Output reverts.         Returns a boolean otherwise.
     * @param _l2OutputIndex Index of the L2 output to check.
     */
    isOutputFinalized(
      _l2OutputIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    l2Oracle(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Address of the L2 account which initiated a withdrawal in this transaction.         If the of this variable is the default L2 sender address, then we are NOT inside of         a call to finalizeWithdrawalTransaction.
     */
    l2Sender(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Message relayer to allowed immediate withdraw.
     */
    messageRelayer(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Computes the minimum gas limit for a deposit.         The minimum gas limit linearly increases based on the size of the calldata.         This is to prevent users from creating L2 resource usage without paying for it.         This function can be used when interacting with the portal to ensure forwards         compatibility.
     * @param _byteCount Number of bytes in the calldata.
     */
    minimumGasLimit(
      _byteCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    /**
     * EIP-1559 style gas parameters.
     */
    params(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        prevBaseFee: BigNumber;
        prevBoughtGas: BigNumber;
        prevBlockNum: BigNumber;
      }
    >;

    /**
     * Pauses withdrawals.
     */
    pause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Determines if cross domain messaging is paused.         When set to true, withdrawals are paused.         This may be removed in the future.
     */
    paused(overrides?: CallOverrides): Promise<[boolean]>;

    proveWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      _l2OutputIndex: BigNumberish,
      _outputRootProof: Types.OutputRootProofStruct,
      _withdrawalProof: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * A mapping of withdrawal hashes to `ProvenWithdrawal` data.
     */
    provenWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        outputRoot: string;
        timestamp: BigNumber;
        l2OutputIndex: BigNumber;
      }
    >;

    /**
     * Set a new message relayer address.         If the zero address is set, no immediate relay of withdrawal messages.
     */
    setMessageRelayer(
      newRelayer: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Getter function for the address of the SystemConfig on this chain.Address of the SystemConfig on this chain.
     */
    systemConfig(overrides?: CallOverrides): Promise<[string]>;

    /**
     * Unpauses withdrawals.
     */
    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    /**
     * Semantic version.
     */
    version(overrides?: CallOverrides): Promise<[string]>;
  };

  /**
   * Address that has the ability to pause and unpause withdrawals. This will be removed in the         future, use `guardian` instead.
   */
  GUARDIAN(overrides?: CallOverrides): Promise<string>;

  /**
   * Address of the L2OutputOracle contract. This will be removed in the         future, use `l2Oracle` instead.
   */
  L2_ORACLE(overrides?: CallOverrides): Promise<string>;

  /**
   * Address of the SystemConfig contract. This will be removed in the         future, use `systemConfig` instead.
   */
  SYSTEM_CONFIG(overrides?: CallOverrides): Promise<string>;

  /**
   * Accepts deposits of ETH and data, and emits a TransactionDeposited event for use in         deriving deposit transactions. Note that if a deposit is made by a contract, its         address will be aliased when retrieved using `tx.origin` or `msg.sender`. Consider         using the CrossDomainMessenger contracts for a simpler developer experience.
   * @param _data Data to trigger the recipient with.
   * @param _gasLimit Amount of L2 gas to purchase by burning gas on L1.
   * @param _isCreation Whether or not the transaction is a contract creation.
   * @param _to Target address on L2.
   * @param _value ETH value to send to the recipient.
   */
  depositTransaction(
    _to: string,
    _value: BigNumberish,
    _gasLimit: BigNumberish,
    _isCreation: boolean,
    _data: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Accepts ETH value without triggering a deposit to L2.         This function mainly exists for the sake of the migration between the legacy         Optimism system and Bedrock.
   */
  donateETH(
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  finalizeWithdrawalTransaction(
    _tx: Types.WithdrawalTransactionStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  finalizeWithdrawalTransactions(
    _txs: Types.WithdrawalTransactionStruct[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * A list of withdrawal hashes which have been successfully finalized.
   */
  finalizedWithdrawals(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
   */
  guardian(overrides?: CallOverrides): Promise<string>;

  /**
   * Initializer.
   */
  initialize(
    _paused: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Initalize with setting messager relayer
   */
  initializeWithRelayer(
    _paused: boolean,
    _messageRelayer: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Determine if a given output is finalized.         Reverts if the call to L2_ORACLE.getL2Output reverts.         Returns a boolean otherwise.
   * @param _l2OutputIndex Index of the L2 output to check.
   */
  isOutputFinalized(
    _l2OutputIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
   */
  l2Oracle(overrides?: CallOverrides): Promise<string>;

  /**
   * Address of the L2 account which initiated a withdrawal in this transaction.         If the of this variable is the default L2 sender address, then we are NOT inside of         a call to finalizeWithdrawalTransaction.
   */
  l2Sender(overrides?: CallOverrides): Promise<string>;

  /**
   * Message relayer to allowed immediate withdraw.
   */
  messageRelayer(overrides?: CallOverrides): Promise<string>;

  /**
   * Computes the minimum gas limit for a deposit.         The minimum gas limit linearly increases based on the size of the calldata.         This is to prevent users from creating L2 resource usage without paying for it.         This function can be used when interacting with the portal to ensure forwards         compatibility.
   * @param _byteCount Number of bytes in the calldata.
   */
  minimumGasLimit(
    _byteCount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  /**
   * EIP-1559 style gas parameters.
   */
  params(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      prevBaseFee: BigNumber;
      prevBoughtGas: BigNumber;
      prevBlockNum: BigNumber;
    }
  >;

  /**
   * Pauses withdrawals.
   */
  pause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Determines if cross domain messaging is paused.         When set to true, withdrawals are paused.         This may be removed in the future.
   */
  paused(overrides?: CallOverrides): Promise<boolean>;

  proveWithdrawalTransaction(
    _tx: Types.WithdrawalTransactionStruct,
    _l2OutputIndex: BigNumberish,
    _outputRootProof: Types.OutputRootProofStruct,
    _withdrawalProof: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * A mapping of withdrawal hashes to `ProvenWithdrawal` data.
   */
  provenWithdrawals(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber] & {
      outputRoot: string;
      timestamp: BigNumber;
      l2OutputIndex: BigNumber;
    }
  >;

  /**
   * Set a new message relayer address.         If the zero address is set, no immediate relay of withdrawal messages.
   */
  setMessageRelayer(
    newRelayer: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Getter function for the address of the SystemConfig on this chain.Address of the SystemConfig on this chain.
   */
  systemConfig(overrides?: CallOverrides): Promise<string>;

  /**
   * Unpauses withdrawals.
   */
  unpause(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  /**
   * Semantic version.
   */
  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    /**
     * Address that has the ability to pause and unpause withdrawals. This will be removed in the         future, use `guardian` instead.
     */
    GUARDIAN(overrides?: CallOverrides): Promise<string>;

    /**
     * Address of the L2OutputOracle contract. This will be removed in the         future, use `l2Oracle` instead.
     */
    L2_ORACLE(overrides?: CallOverrides): Promise<string>;

    /**
     * Address of the SystemConfig contract. This will be removed in the         future, use `systemConfig` instead.
     */
    SYSTEM_CONFIG(overrides?: CallOverrides): Promise<string>;

    /**
     * Accepts deposits of ETH and data, and emits a TransactionDeposited event for use in         deriving deposit transactions. Note that if a deposit is made by a contract, its         address will be aliased when retrieved using `tx.origin` or `msg.sender`. Consider         using the CrossDomainMessenger contracts for a simpler developer experience.
     * @param _data Data to trigger the recipient with.
     * @param _gasLimit Amount of L2 gas to purchase by burning gas on L1.
     * @param _isCreation Whether or not the transaction is a contract creation.
     * @param _to Target address on L2.
     * @param _value ETH value to send to the recipient.
     */
    depositTransaction(
      _to: string,
      _value: BigNumberish,
      _gasLimit: BigNumberish,
      _isCreation: boolean,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Accepts ETH value without triggering a deposit to L2.         This function mainly exists for the sake of the migration between the legacy         Optimism system and Bedrock.
     */
    donateETH(overrides?: CallOverrides): Promise<void>;

    finalizeWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    finalizeWithdrawalTransactions(
      _txs: Types.WithdrawalTransactionStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * A list of withdrawal hashes which have been successfully finalized.
     */
    finalizedWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    guardian(overrides?: CallOverrides): Promise<string>;

    /**
     * Initializer.
     */
    initialize(_paused: boolean, overrides?: CallOverrides): Promise<void>;

    /**
     * Initalize with setting messager relayer
     */
    initializeWithRelayer(
      _paused: boolean,
      _messageRelayer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Determine if a given output is finalized.         Reverts if the call to L2_ORACLE.getL2Output reverts.         Returns a boolean otherwise.
     * @param _l2OutputIndex Index of the L2 output to check.
     */
    isOutputFinalized(
      _l2OutputIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    l2Oracle(overrides?: CallOverrides): Promise<string>;

    /**
     * Address of the L2 account which initiated a withdrawal in this transaction.         If the of this variable is the default L2 sender address, then we are NOT inside of         a call to finalizeWithdrawalTransaction.
     */
    l2Sender(overrides?: CallOverrides): Promise<string>;

    /**
     * Message relayer to allowed immediate withdraw.
     */
    messageRelayer(overrides?: CallOverrides): Promise<string>;

    /**
     * Computes the minimum gas limit for a deposit.         The minimum gas limit linearly increases based on the size of the calldata.         This is to prevent users from creating L2 resource usage without paying for it.         This function can be used when interacting with the portal to ensure forwards         compatibility.
     * @param _byteCount Number of bytes in the calldata.
     */
    minimumGasLimit(
      _byteCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * EIP-1559 style gas parameters.
     */
    params(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        prevBaseFee: BigNumber;
        prevBoughtGas: BigNumber;
        prevBlockNum: BigNumber;
      }
    >;

    /**
     * Pauses withdrawals.
     */
    pause(overrides?: CallOverrides): Promise<void>;

    /**
     * Determines if cross domain messaging is paused.         When set to true, withdrawals are paused.         This may be removed in the future.
     */
    paused(overrides?: CallOverrides): Promise<boolean>;

    proveWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      _l2OutputIndex: BigNumberish,
      _outputRootProof: Types.OutputRootProofStruct,
      _withdrawalProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * A mapping of withdrawal hashes to `ProvenWithdrawal` data.
     */
    provenWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber] & {
        outputRoot: string;
        timestamp: BigNumber;
        l2OutputIndex: BigNumber;
      }
    >;

    /**
     * Set a new message relayer address.         If the zero address is set, no immediate relay of withdrawal messages.
     */
    setMessageRelayer(
      newRelayer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Getter function for the address of the SystemConfig on this chain.Address of the SystemConfig on this chain.
     */
    systemConfig(overrides?: CallOverrides): Promise<string>;

    /**
     * Unpauses withdrawals.
     */
    unpause(overrides?: CallOverrides): Promise<void>;

    /**
     * Semantic version.
     */
    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "MessageRelayerSet(address)"(
      relayer?: string | null
    ): MessageRelayerSetEventFilter;
    MessageRelayerSet(relayer?: string | null): MessageRelayerSetEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "TransactionDeposited(address,address,uint256,bytes)"(
      from?: string | null,
      to?: string | null,
      version?: BigNumberish | null,
      opaqueData?: null
    ): TransactionDepositedEventFilter;
    TransactionDeposited(
      from?: string | null,
      to?: string | null,
      version?: BigNumberish | null,
      opaqueData?: null
    ): TransactionDepositedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "WithdrawalFinalized(bytes32,bool)"(
      withdrawalHash?: BytesLike | null,
      success?: null
    ): WithdrawalFinalizedEventFilter;
    WithdrawalFinalized(
      withdrawalHash?: BytesLike | null,
      success?: null
    ): WithdrawalFinalizedEventFilter;

    "WithdrawalProven(bytes32,address,address)"(
      withdrawalHash?: BytesLike | null,
      from?: string | null,
      to?: string | null
    ): WithdrawalProvenEventFilter;
    WithdrawalProven(
      withdrawalHash?: BytesLike | null,
      from?: string | null,
      to?: string | null
    ): WithdrawalProvenEventFilter;
  };

  estimateGas: {
    /**
     * Address that has the ability to pause and unpause withdrawals. This will be removed in the         future, use `guardian` instead.
     */
    GUARDIAN(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Address of the L2OutputOracle contract. This will be removed in the         future, use `l2Oracle` instead.
     */
    L2_ORACLE(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Address of the SystemConfig contract. This will be removed in the         future, use `systemConfig` instead.
     */
    SYSTEM_CONFIG(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Accepts deposits of ETH and data, and emits a TransactionDeposited event for use in         deriving deposit transactions. Note that if a deposit is made by a contract, its         address will be aliased when retrieved using `tx.origin` or `msg.sender`. Consider         using the CrossDomainMessenger contracts for a simpler developer experience.
     * @param _data Data to trigger the recipient with.
     * @param _gasLimit Amount of L2 gas to purchase by burning gas on L1.
     * @param _isCreation Whether or not the transaction is a contract creation.
     * @param _to Target address on L2.
     * @param _value ETH value to send to the recipient.
     */
    depositTransaction(
      _to: string,
      _value: BigNumberish,
      _gasLimit: BigNumberish,
      _isCreation: boolean,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Accepts ETH value without triggering a deposit to L2.         This function mainly exists for the sake of the migration between the legacy         Optimism system and Bedrock.
     */
    donateETH(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    finalizeWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    finalizeWithdrawalTransactions(
      _txs: Types.WithdrawalTransactionStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * A list of withdrawal hashes which have been successfully finalized.
     */
    finalizedWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    guardian(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Initializer.
     */
    initialize(
      _paused: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Initalize with setting messager relayer
     */
    initializeWithRelayer(
      _paused: boolean,
      _messageRelayer: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Determine if a given output is finalized.         Reverts if the call to L2_ORACLE.getL2Output reverts.         Returns a boolean otherwise.
     * @param _l2OutputIndex Index of the L2 output to check.
     */
    isOutputFinalized(
      _l2OutputIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    l2Oracle(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Address of the L2 account which initiated a withdrawal in this transaction.         If the of this variable is the default L2 sender address, then we are NOT inside of         a call to finalizeWithdrawalTransaction.
     */
    l2Sender(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Message relayer to allowed immediate withdraw.
     */
    messageRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Computes the minimum gas limit for a deposit.         The minimum gas limit linearly increases based on the size of the calldata.         This is to prevent users from creating L2 resource usage without paying for it.         This function can be used when interacting with the portal to ensure forwards         compatibility.
     * @param _byteCount Number of bytes in the calldata.
     */
    minimumGasLimit(
      _byteCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * EIP-1559 style gas parameters.
     */
    params(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Pauses withdrawals.
     */
    pause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    /**
     * Determines if cross domain messaging is paused.         When set to true, withdrawals are paused.         This may be removed in the future.
     */
    paused(overrides?: CallOverrides): Promise<BigNumber>;

    proveWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      _l2OutputIndex: BigNumberish,
      _outputRootProof: Types.OutputRootProofStruct,
      _withdrawalProof: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * A mapping of withdrawal hashes to `ProvenWithdrawal` data.
     */
    provenWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Set a new message relayer address.         If the zero address is set, no immediate relay of withdrawal messages.
     */
    setMessageRelayer(
      newRelayer: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    /**
     * Getter function for the address of the SystemConfig on this chain.Address of the SystemConfig on this chain.
     */
    systemConfig(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * Unpauses withdrawals.
     */
    unpause(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    /**
     * Semantic version.
     */
    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Address that has the ability to pause and unpause withdrawals. This will be removed in the         future, use `guardian` instead.
     */
    GUARDIAN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Address of the L2OutputOracle contract. This will be removed in the         future, use `l2Oracle` instead.
     */
    L2_ORACLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Address of the SystemConfig contract. This will be removed in the         future, use `systemConfig` instead.
     */
    SYSTEM_CONFIG(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Accepts deposits of ETH and data, and emits a TransactionDeposited event for use in         deriving deposit transactions. Note that if a deposit is made by a contract, its         address will be aliased when retrieved using `tx.origin` or `msg.sender`. Consider         using the CrossDomainMessenger contracts for a simpler developer experience.
     * @param _data Data to trigger the recipient with.
     * @param _gasLimit Amount of L2 gas to purchase by burning gas on L1.
     * @param _isCreation Whether or not the transaction is a contract creation.
     * @param _to Target address on L2.
     * @param _value ETH value to send to the recipient.
     */
    depositTransaction(
      _to: string,
      _value: BigNumberish,
      _gasLimit: BigNumberish,
      _isCreation: boolean,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Accepts ETH value without triggering a deposit to L2.         This function mainly exists for the sake of the migration between the legacy         Optimism system and Bedrock.
     */
    donateETH(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    finalizeWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    finalizeWithdrawalTransactions(
      _txs: Types.WithdrawalTransactionStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * A list of withdrawal hashes which have been successfully finalized.
     */
    finalizedWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    guardian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Initializer.
     */
    initialize(
      _paused: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Initalize with setting messager relayer
     */
    initializeWithRelayer(
      _paused: boolean,
      _messageRelayer: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Determine if a given output is finalized.         Reverts if the call to L2_ORACLE.getL2Output reverts.         Returns a boolean otherwise.
     * @param _l2OutputIndex Index of the L2 output to check.
     */
    isOutputFinalized(
      _l2OutputIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Getter function for the address of the L2OutputOracle on this chain.Address of the L2OutputOracle on this chain.
     */
    l2Oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Address of the L2 account which initiated a withdrawal in this transaction.         If the of this variable is the default L2 sender address, then we are NOT inside of         a call to finalizeWithdrawalTransaction.
     */
    l2Sender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Message relayer to allowed immediate withdraw.
     */
    messageRelayer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Computes the minimum gas limit for a deposit.         The minimum gas limit linearly increases based on the size of the calldata.         This is to prevent users from creating L2 resource usage without paying for it.         This function can be used when interacting with the portal to ensure forwards         compatibility.
     * @param _byteCount Number of bytes in the calldata.
     */
    minimumGasLimit(
      _byteCount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * EIP-1559 style gas parameters.
     */
    params(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Pauses withdrawals.
     */
    pause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Determines if cross domain messaging is paused.         When set to true, withdrawals are paused.         This may be removed in the future.
     */
    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proveWithdrawalTransaction(
      _tx: Types.WithdrawalTransactionStruct,
      _l2OutputIndex: BigNumberish,
      _outputRootProof: Types.OutputRootProofStruct,
      _withdrawalProof: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * A mapping of withdrawal hashes to `ProvenWithdrawal` data.
     */
    provenWithdrawals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Set a new message relayer address.         If the zero address is set, no immediate relay of withdrawal messages.
     */
    setMessageRelayer(
      newRelayer: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Getter function for the address of the SystemConfig on this chain.Address of the SystemConfig on this chain.
     */
    systemConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * Unpauses withdrawals.
     */
    unpause(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    /**
     * Semantic version.
     */
    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
